# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (ensure it's compatible with Playwright)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust to the version you're using in your repo

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Install Playwright browser dependencies
      - name: Install Playwright dependencies
        run: |
          npx playwright install --with-deps

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: npx playwright test tests/sample.spec.js
